import { Link } from "@tanstack/react-router";
import { ArrowRight, BarChart3, BookOpenCheck, CalendarDays, CheckCircle2, Clock3, FileSearch, Focus, Sparkles, Text, TrendingUp, Zap } from "lucide-react";
import heroImage from "@/assets/student-ai-hero.jpg";
import { recentNotes, recentPyqs } from "@/lib/mock-data";
import { Button } from "@/components/ui/button";

const weeks = ["DSA Basics + Practice", "DBMS Concepts + PYQs", "OS Core Topics + Revision", "Full Revision + Mock Tests"];
function ToolCard({ tone, icon: Icon, title, description, to, action, children }: { tone: string; icon: typeof CalendarDays; title: string; description: string; to: "/study-plan" | "/pyq-analysis" | "/notes-summarizer"; action: string; children: React.ReactNode }) {
  return <article className={`tool-card ${tone}`}><div className="tool-heading"><span className="tool-icon"><Icon /></span><div><h2>{title}</h2><p>{description}</p></div></div><div className="tool-preview">{children}</div><Button asChild className="tool-action"><Link to={to}>{action}<ArrowRight /></Link></Button></article>;
}
export function Dashboard() {
  return <div className="dashboard page-enter"><section className="hero"><div className="hero-copy"><span className="eyebrow"><Sparkles /> Your everyday study companion</span><h1>Study Smarter,<br /><span>Not Harder</span></h1><p>Your AI-powered study assistant to plan better, understand patterns and learn faster.</p><div className="benefits"><span><Zap /> Save Time</span><span><Focus /> Stay Focused</span><span><TrendingUp /> Achieve More</span></div></div><div className="hero-art"><img src={heroImage} width={1280} height={960} alt="Student learning with a friendly AI study companion" /><span className="doodle doodle-one">ideas → action</span><span className="doodle doodle-two">you've got this!</span></div></section>
  <section className="section-heading"><div><span className="eyebrow">Choose your next step</span><h2>How can I help today?</h2></div><p>Three focused tools, one calmer way to prepare.</p></section>
  <section className="tools-grid">
    <ToolCard tone="tool-blue" icon={CalendarDays} title="Study Plan Generator" description="Build a personalized schedule around your goals, subjects and time." to="/study-plan" action="View full plan"><div className="mini-chat"><p><span>AI</span> What would you like to achieve?</p><p className="student">Semester exams in 4 weeks.</p></div><div className="mini-plan">{weeks.map((week, index) => <div key={week}><b>W{index + 1}</b><span>{week}</span><i /></div>)}</div></ToolCard>
    <ToolCard tone="tool-purple" icon={FileSearch} title="PYQ Analysis" description="Find recurring topics, trends and useful question patterns." to="/pyq-analysis" action="Analyze PYQs"><div className="mini-upload"><FileSearch /><b>Drop PYQs here</b><small>PDF or image</small></div><div className="mini-stats"><span><b>78%</b> syllabus coverage</span><span><b>22%</b> arrays</span></div></ToolCard>
    <ToolCard tone="tool-green" icon={Text} title="Notes Summarizer" description="Turn long notes into crisp, easy-to-revise study material." to="/notes-summarizer" action="Summarize notes"><div className="mini-tabs"><span>Text</span><span>PDF</span><span>Image</span><span>Link</span></div><div className="mini-summary"><b>Key points</b><p>1. Clear explanations</p><p>2. Important facts</p><p>3. Quick revision</p></div></ToolCard>
  </section>
  <section className="insights-band"><div className="section-heading compact"><div><span className="eyebrow">Your study pulse</span><h2>Progress at a glance</h2></div><span className="sample-note">Sample dashboard data</span></div><div className="metrics-grid">{[{value:"1,280",label:"Questions analyzed",icon:FileSearch},{value:"18",label:"Total topics",icon:BookOpenCheck},{value:"5",label:"Years analyzed",icon:CalendarDays},{value:"Medium",label:"Average difficulty",icon:BarChart3}].map(({value,label,icon:Icon}) => <div className="metric" key={label}><span><Icon /></span><div><strong>{value}</strong><small>{label}</small></div></div>)}</div><div className="quick-insights"><h3>Quick Insights</h3><div className="insight-list">{["Arrays and Trees appear often across past papers.","Most questions sit at a medium difficulty level.","Repeated concepts are ideal for focused revision.","Graph questions are becoming more frequent."].map((item,index)=><div key={item}><span>{["💡","📊","🔁","📈"][index]}</span><p>{item}</p></div>)}</div></div></section>
  <section className="activity-grid"><article className="activity-panel"><div className="panel-title"><div><span className="eyebrow">Latest analysis</span><h2>Recent PYQs</h2></div><Link to="/pyq-analysis">View all <ArrowRight /></Link></div><div className="activity-list">{recentPyqs.map(([year,subject,topic])=><div key={`${year}-${topic}`}><span className="year-chip">{year}</span><div><strong>{subject}</strong><small>{topic}</small></div><CheckCircle2 /></div>)}</div></article><article className="activity-panel"><div className="panel-title"><div><span className="eyebrow">Ready to revise</span><h2>Recent Notes</h2></div><Link to="/notes-summarizer">Open tool <ArrowRight /></Link></div><div className="notes-list">{recentNotes.map((note,index)=><div key={note}><span><BookOpenCheck /></span><div><strong>{note.split(" — ")[0]}</strong><small>{note.split(" — ")[1]}</small></div><small><Clock3 /> {index + 2}d ago</small></div>)}</div></article></section></div>;
}
